/********************************************************************/
/* Program     : HSC200A                                            */
/* Purpose     : Sales Order Processing.                            */
/* System      : HSV - Voucher Tracking and Control                 */
/* Date        : March 1999                                         */
/********************************************************************/

             PGM
             dspmsg
             ENDPGM
