<?php
/*
 * Created on 28 sept. 06
 *
 * To change the template for this generated file go to
 * Window - Preferences - PHPeclipse - PHP - Code Templates
 */
session_start();

if ($_SESSION['md5'] == '') {
	header("Location: page_erreur.php?code=3");
	exit;
}

include_once "properties.inc.php";

$date_validation = date("Y-m-d");

$connexion = mysql_connect($mysql_hostname, $mysql_login,$mysql_passwd); // Bien Authentifié sur mysql

if ($connexion == '') {
	header("Location: page_erreur.php?code=15");
	exit;
	//echo "Probléme de connexion à mysql, ressayer";
	//exit;
}

if (mysql_select_db($mysql_database, $connexion)) { // Bien authentifié à la base download
	$ip = get_ip();
	$md5 = $_SESSION['md5'];
	if (isset ($_POST["envoi_cd"])) {
		$envoi_cd = $_POST["envoi_cd"];
	} else {
		$envoi_cd = 0;
	}
	$sql = "update client set valider=1, date_validation='$date_validation', adresse_ip='$ip', envoi_cd=$envoi_cd where md5='$md5';";
	if (mysql_query($sql, $connexion) == false) {
		header("Location: page_erreur.php?code=13");
		exit;
	}

	//envoi du mail à Arcad
	$sql = "select * from client where md5='$md5';";

	$result = mysql_query($sql, $connexion);

	if (mysql_num_rows($result) != 1) {
		header("Location: page_erreur.php?code=50");
		exit;
	}

	$result = mysql_fetch_array($result);

	$nom_societe = $result['nom_societe'];
	$numero_facture = $result['num_facture'];
	$montant_facture = $result['montant_facture'];
	$produit = $result['produit'];
	$envoi_cd = $result['envoi_cd'];
	$mail_client = $result['mail_client'];
	
	if ($envoi_cd ==1) {$cd="OUI";}else{$cd="NON";}
	
	$_SESSION['produit'] = $produit;
	
	
	if (isset ($mail_client) and $mail_client <> '' and $mail_from <> '') {

		$message_mail = "This message has been automatically " .
			"generated by the download server, following customer validation : ". "\r\n \r\n" . 
			"Customer validation : " . $nom_societe . "\r\n" .
			"Invoice number : " . $numero_facture . "\r\n" .
			"Invoice amount : " . $montant_facture . "\r\n" .
			"Product : " . $produit . "\r\n" .
			/*"Envoyer un cd gratuit : " . $cd . "\r\n" .*/
			"IP address : " . $ip . "\r\n";

	$headers = 'From: ' . $mail_from . "\r\n" .
	'Reply-To: ' . $mail_from . "\r\n" .
	'X-Mailer: PHP/' . phpversion();

		Mail("aguignon@arcadsoftware.com", $mail_subject_admin . $nom_societe, $message_mail,$headers);

	}

} else {
	header("Location: page_erreur.php?code=16");
	exit;
	//echo "Probléme de connexion à la base download, ressayer";
	//exit;
}
?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
<title>Document sans titre</title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<link rel="stylesheet" href="style.css" type="text/css">
</head>

<BODY topmargin="0" leftmargin="0" bgcolor="#ffffff">
    <!--BANDEAU TITRE SLOGAN-->
    <TABLE align="Center"><tr><td width="607">
    <TABLE height="87" width="600" cellspacing="0" cellpadding="0" class='fond_image'>
      <tr class="mini" height="20">
        <td>&nbsp;</td>
        <td>&nbsp;</td>
      </tr>
      <tr>
        <td width="160">&nbsp;</td>
        <td class="societe" valign="top">Arcad Software<br>
        <span class="slogan">Downloading file : </span></td>
      </tr>
    </table>
    <!--FIN - BANDEAU TITRE SLOGAN-->
    <!--Grand TITRE et Petit Texte Haut-->
	<br>
    <TABLE width="600" bgcolor="#ffffff" cellspacing="0" cellpadding="0" >
      <tr class="GDTitre">
        <td>&nbsp;Download</td>
      </tr>
	</table>
    <!--FIN - Grand TITRE et Petit Texte Haut-->
<p align="center"><strong>Thank you for validating the form : </strong></p>
<p align="center"><strong><a href="download.php">Click here to download your product : </a></strong></p>
<p align="center">&nbsp;</p>
<p align="center"><font size="2">The file you are about to download is a .zip archive or an .iso image.</font></p>
</td></tr></table>
</body>
</html>