      ****************************************************************
      * APPLICATION NAME...........: . ALL APPLICATIONS              *
      * COPY NAME..................: . WKSPECNAMES                   *
      * COPY TYPE..................: . DEFINITION GENERAL FIELD      *
      * FUNCTION...................: . SPECIAL-NAMES                 *
      * COPY LOCATION..............: . AFTER OBJECT-COMPUTER         *
      ****************************************************************
       SPECIAL-NAMES.   I-O-FEEDBACK    IS IO-INFO
                        OPEN-FEEDBACK   IS OPEN-INFO
                        CONSOLE         IS OPERATEUR
                        LOCAL-DATA      IS LDA
                        REQUESTOR       IS ECRAN
                        UPSI-0          IS SW0
                            ON STATUS   IS SW0-ON
                        UPSI-1          IS SW1
                            ON STATUS   IS SW1-ON
                        UPSI-2          IS SW2
                            ON STATUS   IS SW2-ON
                        UPSI-3          IS SW3
                            ON STATUS   IS SW3-ON
                        UPSI-4          IS SW4
                            ON STATUS   IS SW4-ON
                        UPSI-5          IS SW5
                            ON STATUS   IS SW5-ON
                        UPSI-6          IS SW6
                            ON STATUS   IS SW6-ON
                        UPSI-7          IS SW7
                            ON STATUS   IS SW7-ON
                        SYSTEM-SHUTDOWN IS SYSTEME-STATUS
                              ON STATUS IS FIN-SYSTEME
                        DECIMAL-POINT   IS COMMA.
      *
